### ISSUE TITLE
Problem with serialization

### ISSUE THREAD

**Issue by EdgarAP** [dpdearing/android-gps-emulator#12]
When I open the browser it shows the map, but at top it says "Error making connection on port 5554: The call failed on the server; see server log for details", and the log in the console is:

2016-07-12 11:44:20.210:INFO::jetty-7.x.y-SNAPSHOT
2016-07-12 11:44:20.658:INFO::Extract jar:file:/C:/Users/Edgar/android-gps-emulator-0.1.0.war!/ to C:\Users\Edgar\AppData\Local\Temp\jetty-0.0.0.0-8080-android-gps-emulator-0.1.0.war-_-any-\webapp
2016-07-12 11:44:21.397:INFO::NO JSP Support for /, did not find org.apache.jasper.servlet.JspServlet
2016-07-12 11:44:21.427:INFO::started o.e.j.w.WebAppContext{/,file:/C:/Users/Edgar/AppData/Local/Temp/jetty-0.0.0.0-8080-android-gps-emulator-0.1.0.war-_-any-/webapp/},file:/C:/Users/Edgar/android-gps-emulator-0.1.0.war
2016-07-12 11:44:21.508:INFO::Started SelectChannelConnector@0.0.0.0:8080
Wrapper: java.net.ConnectException: Connection refused: connect
2016-07-12 11:44:24.380:WARN:/:Exception while dispatching incoming RPC call
com.google.gwt.user.client.rpc.SerializationException: Type 'java.net.ConnectException' was not included in the set of types which can be serialized by this SerializationPolicy or its Class object could not be loaded. For security purposes, this type will not be serialized.: instance = java.net.ConnectException: Connection refused: connect
        at com.google.gwt.user.server.rpc.impl.ServerSerializationStreamWriter.serialize(ServerSerializationStreamWriter.java:610)
        at com.google.gwt.user.client.rpc.impl.AbstractSerializationStreamWriter.writeObject(AbstractSerializationStreamWriter.java:129)
        at com.google.gwt.user.server.rpc.impl.ServerSerializationStreamWriter$ValueWriter$8.write(ServerSerializationStreamWriter.java:152)
        at com.google.gwt.user.server.rpc.impl.ServerSerializationStreamWriter.serializeValue(ServerSerializationStreamWriter.java:534)
        at com.google.gwt.user.server.rpc.RPC.encodeResponse(RPC.java:609)
        at com.google.gwt.user.server.rpc.RPC.encodeResponseForFailure(RPC.java:383)
        at com.google.gwt.user.server.rpc.RPC.invokeAndEncodeResponse(RPC.java:581)
        at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:188)
        at com.google.gwt.user.server.rpc.RemoteServiceServlet.processPost(RemoteServiceServlet.java:224)
        at com.google.gwt.user.server.rpc.AbstractRemoteServiceServlet.doPost(AbstractRemoteServiceServlet.java:62)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:534)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:476)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:119)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:517)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:934)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:404)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:184)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:869)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
        at org.eclipse.jetty.server.Server.handle(Server.java:346)
        at org.eclipse.jetty.server.HttpConnection.handleRequest(HttpConnection.java:581)
        at org.eclipse.jetty.server.HttpConnection$RequestHandler.content(HttpConnection.java:1057)
        at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:807)
        at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:220)
        at org.eclipse.jetty.server.HttpConnection.handle(HttpConnection.java:411)
        at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:526)
        at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:41)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:528)
        at java.lang.Thread.run(Unknown Source)

**Comment by dpdearing** [comment]
Is your emulator running?

I get this message when the Android emulator is not up and running.

If you get the emulator running _after_ launching the browser you can just click the "Change Emulator Port" button (which should probably just read "Connect to port")

**Comment by dpdearing** [comment]
@EdgarAP I'm going to mark this as closed unless you can tell me if this happens when the emulator is already running and you try to connect.
